sudo: false
language: python
matrix:
  include:
  - python: 3.6
  - python: 3.7
install:
- travis_retry pip install . pytest isort black
- pip list
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
